import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/global.css";
import "@/styles/wave.css";
import { Providers } from "@/components/functional/providers";
import Header from "@/components/layouts/Header";
import SectionContainer from "@/components/layouts/SectionContainer";
import Footer from "@/components/layouts/Footer";
import siteMetadata from "@/siteMetadata";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang={siteMetadata.language} suppressHydrationWarning>
      <meta
        name="theme-color"
        media="(prefers-color-scheme: light)"
        content="#fff"
      />
      <meta
        name="theme-color"
        media="(prefers-color-scheme: dark)"
        content="#000"
      />
      <body
        className={
          (inter.className,
          "bg-gray-50 text-gray-600 antialiased dark:bg-gray-800 dark:text-gray-200")
        }
      >
        <SectionContainer>
          <Providers>
            <div className="flex h-screen flex-col justify-between">
              <Header />
              <main className="mb-auto">{children}</main>
              <Footer />
            </div>
          </Providers>
        </SectionContainer>
      </body>
    </html>
  );
}
